### ISSUE TITLE
Fireflies color scheme produces lots of warnings in Qt applications.

### ISSUE THREAD

**Issue by sommerluk** [rkstrdee/Fireflies#1]
Fireflies color scheme produces lots of warnings in Qt applications.

**Steps to reproduce:**
– Select the Fireflies color scheme in KDE’s system settings.
– Start a Qt application in a terminal.

**Actual result:**
There appears many times the following warning:

```
"Color" - conversion from "rgb112,111,110" to QColor failed  (integer conversion failed)`
```

**Expected result:**
The Qt application does not produce any warnings, just like with other color schemes.

**Fix:**
In `color-schemes/Fireflies.colors` change the following line
```
Color=rgb112,111,110
```
into
```
Color=112,111,110
```

**Comment by ddh4r4m** [comment]
My bad, thanks for poiniting it out, the issue has been resolved.
